name: Run Gradle on PRs
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set env
        run: echo "APP_VERSION=1.0.2" >> $GITHUB_ENV
      - name: Create k8s yaml
        run: |
          curl -L https://github.com/a8m/envsubst/releases/download/v1.2.0/envsubst-`uname -s`-`uname -m` -o envsubst
          chmod +x envsubst
          sudo mv envsubst /usr/local/bin
          envsubst < ./k8s/app.yaml > app.yaml
          cat app.yaml
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.truongnq.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          tags: registry.truongnq.com/simple-http-server:${{ env.APP_VERSION }}
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f app.yaml